// Generated by tools/build.py from knowledge-graph.json. Do not edit.
window.COURSE = window.COURSE || {};
COURSE.graph = {
 "modules": {
  "F1": "Foundations I - Cost and counting",
  "F2": "Foundations II - Proving an algorithm is correct",
  "F3": "Foundations III - What the machine actually does",
  "M1": "Hashing",
  "M2": "Two pointers",
  "M3": "Sliding window",
  "M4": "Binary search",
  "M5": "Stacks and monotonic stack",
  "M6": "Linked lists",
  "M7": "Trees",
  "M8": "Heaps and top-K",
  "M9": "Backtracking",
  "M10": "Graphs",
  "M11": "Dynamic programming",
  "M12": "Intervals and greedy"
 },
 "topics": {
  "F01": {
   "title": "Big-O as a growth rate",
   "module": "F1",
   "prereqs": [],
   "key_prereqs": [],
   "href": "lessons/F01-big-o-as-a-growth-rate.html"
  },
  "F02": {
   "title": "Logarithms as repeated halving",
   "module": "F1",
   "prereqs": [
    "F01"
   ],
   "key_prereqs": [
    "F01"
   ],
   "href": "lessons/F02-logarithms-as-repeated-halving.html"
  },
  "F03": {
   "title": "Arithmetic and geometric sums",
   "module": "F1",
   "prereqs": [
    "F01"
   ],
   "key_prereqs": [
    "F01"
   ],
   "href": "lessons/F03-arithmetic-and-geometric-sums.html"
  },
  "F14": {
   "title": "Counting: subsets, permutations, combinations",
   "module": "F1",
   "prereqs": [
    "F01"
   ],
   "key_prereqs": [
    "F01"
   ],
   "href": "lessons/F14-counting-subsets-permutations-combinatio.html"
  },
  "F07": {
   "title": "Loop invariants",
   "module": "F2",
   "prereqs": [
    "F01"
   ],
   "key_prereqs": [],
   "href": "lessons/F07-loop-invariants.html"
  },
  "F08": {
   "title": "Induction and recursive correctness",
   "module": "F2",
   "prereqs": [
    "F07"
   ],
   "key_prereqs": [
    "F07"
   ],
   "href": "lessons/F08-induction-and-recursive-correctness.html"
  },
  "F09": {
   "title": "Search-space elimination",
   "module": "F2",
   "prereqs": [
    "F07"
   ],
   "key_prereqs": [
    "F07"
   ],
   "href": "lessons/F09-search-space-elimination.html"
  },
  "F13": {
   "title": "Monotone predicates",
   "module": "F2",
   "prereqs": [
    "F07"
   ],
   "key_prereqs": [
    "F07"
   ],
   "href": "lessons/F13-monotone-predicates.html"
  },
  "F10": {
   "title": "Memory model: arrays, references, boxing",
   "module": "F3",
   "prereqs": [
    "F01"
   ],
   "key_prereqs": [
    "F01"
   ],
   "href": "lessons/F10-memory-model-arrays-references-boxing.html"
  },
  "F04": {
   "title": "Amortized analysis",
   "module": "F3",
   "prereqs": [
    "F03",
    "F10"
   ],
   "key_prereqs": [
    "F03"
   ],
   "href": "lessons/F04-amortized-analysis.html"
  },
  "F11": {
   "title": "How a hash table works",
   "module": "F3",
   "prereqs": [
    "F04",
    "F10"
   ],
   "key_prereqs": [
    "F04",
    "F10"
   ],
   "href": "lessons/F11-how-a-hash-table-works.html"
  },
  "F16": {
   "title": "Tree anatomy",
   "module": "F3",
   "prereqs": [
    "F02",
    "F10"
   ],
   "key_prereqs": [
    "F02"
   ],
   "href": "lessons/F16-tree-anatomy.html"
  },
  "F15": {
   "title": "Graph representation",
   "module": "F3",
   "prereqs": [
    "F01",
    "F10"
   ],
   "key_prereqs": [
    "F10"
   ],
   "href": "lessons/F15-graph-representation.html"
  },
  "F05": {
   "title": "Recursion and the call stack",
   "module": "F3",
   "prereqs": [
    "F08",
    "F10"
   ],
   "key_prereqs": [
    "F08"
   ],
   "href": "lessons/F05-recursion-and-the-call-stack.html"
  },
  "F06": {
   "title": "Recurrences via recursion trees",
   "module": "F3",
   "prereqs": [
    "F02",
    "F03",
    "F05"
   ],
   "key_prereqs": [
    "F03",
    "F05"
   ],
   "href": "lessons/F06-recurrences-via-recursion-trees.html"
  },
  "F12": {
   "title": "Sorting cost and the n log n lower bound",
   "module": "F3",
   "prereqs": [
    "F02",
    "F06"
   ],
   "key_prereqs": [
    "F02"
   ],
   "href": "lessons/F12-sorting-cost-and-the-n-log-n-lower-bound.html"
  },
  "P01": {
   "title": "Hash map pattern: complement lookup and counting",
   "module": "M1",
   "prereqs": [
    "F11"
   ],
   "key_prereqs": [
    "F11"
   ],
   "href": "lessons/P01-hash-map-pattern-complement-lookup-and-c.html"
  },
  "P02": {
   "title": "Converging two pointers",
   "module": "M2",
   "prereqs": [
    "F09",
    "F12"
   ],
   "key_prereqs": [
    "F09"
   ],
   "href": "lessons/P02-converging-two-pointers.html"
  },
  "P03": {
   "title": "Same-direction pointers (read/write, fast/slow)",
   "module": "M2",
   "prereqs": [
    "F07"
   ],
   "key_prereqs": [
    "F07"
   ],
   "href": "lessons/P03-same-direction-pointers-read-write-fast.html"
  },
  "P04": {
   "title": "Sliding window",
   "module": "M3",
   "prereqs": [
    "P01",
    "P03",
    "F04"
   ],
   "key_prereqs": [
    "F04",
    "P03"
   ],
   "href": "lessons/P04-sliding-window.html"
  },
  "P05": {
   "title": "Binary search on a sorted array",
   "module": "M4",
   "prereqs": [
    "F02",
    "F13"
   ],
   "key_prereqs": [
    "F13",
    "F07"
   ],
   "href": "lessons/P05-binary-search-on-a-sorted-array.html"
  },
  "P06": {
   "title": "Binary search on the answer space",
   "module": "M4",
   "prereqs": [
    "P05"
   ],
   "key_prereqs": [
    "F13",
    "P05"
   ],
   "href": "lessons/P06-binary-search-on-the-answer-space.html"
  },
  "P07": {
   "title": "Stacks and monotonic stack",
   "module": "M5",
   "prereqs": [
    "F04",
    "F07"
   ],
   "key_prereqs": [
    "F04",
    "F07"
   ],
   "href": "lessons/P07-stacks-and-monotonic-stack.html"
  },
  "P08": {
   "title": "Linked-list manipulation",
   "module": "M6",
   "prereqs": [
    "F10",
    "P03"
   ],
   "key_prereqs": [
    "F10",
    "P03"
   ],
   "href": "lessons/P08-linked-list-manipulation.html"
  },
  "P09": {
   "title": "Tree DFS and BFS",
   "module": "M7",
   "prereqs": [
    "F05",
    "F16"
   ],
   "key_prereqs": [
    "F05",
    "F08"
   ],
   "href": "lessons/P09-tree-dfs-and-bfs.html"
  },
  "P10": {
   "title": "Heaps and top-K",
   "module": "M8",
   "prereqs": [
    "F16",
    "F02"
   ],
   "key_prereqs": [
    "F16"
   ],
   "href": "lessons/P10-heaps-and-top-k.html"
  },
  "P11": {
   "title": "Backtracking",
   "module": "M9",
   "prereqs": [
    "F05",
    "F14"
   ],
   "key_prereqs": [
    "F14",
    "F05"
   ],
   "href": "lessons/P11-backtracking.html"
  },
  "P12": {
   "title": "Graph BFS/DFS and connected components",
   "module": "M10",
   "prereqs": [
    "F15",
    "P09"
   ],
   "key_prereqs": [
    "F15",
    "P09"
   ],
   "href": "lessons/P12-graph-bfs-dfs-and-connected-components.html"
  },
  "P13": {
   "title": "Topological sort",
   "module": "M10",
   "prereqs": [
    "P12"
   ],
   "key_prereqs": [
    "P12"
   ],
   "href": "lessons/P13-topological-sort.html"
  },
  "P14": {
   "title": "Dijkstra",
   "module": "M10",
   "prereqs": [
    "P12",
    "P10"
   ],
   "key_prereqs": [
    "P10",
    "P12"
   ],
   "href": "lessons/P14-dijkstra.html"
  },
  "P15": {
   "title": "Union-find",
   "module": "M10",
   "prereqs": [
    "F16",
    "F15"
   ],
   "key_prereqs": [
    "F16"
   ],
   "href": "lessons/P15-union-find.html"
  },
  "P16": {
   "title": "Dynamic programming",
   "module": "M11",
   "prereqs": [
    "F06",
    "P11"
   ],
   "key_prereqs": [
    "F08",
    "F06",
    "P11"
   ],
   "href": "lessons/P16-dynamic-programming.html"
  },
  "P17": {
   "title": "Intervals and greedy",
   "module": "M12",
   "prereqs": [
    "F12",
    "F07"
   ],
   "key_prereqs": [
    "F12",
    "F07"
   ],
   "href": "lessons/P17-intervals-and-greedy.html"
  }
 }
};
