// Generated by tools/build_problems.py. Edit SUGGESTED there, not here.
window.COURSE = window.COURSE || {};
COURSE.problems = {
 "F01": [
  {
   "name": "217. Contains Duplicate",
   "src": "LeetCode",
   "diff": "Easy",
   "url": "https://leetcode.com/problems/contains-duplicate/",
   "why": "Same answer two ways; time both at n = 100000 and watch the growth rate decide."
  },
  {
   "name": "Distinct Numbers",
   "src": "CSES",
   "diff": "Sorting and Searching",
   "url": "https://cses.fi/problemset/task/1621",
   "why": "n up to 2e5: the constraint rules out the n^2 scan before you write a line."
  },
  {
   "name": "53. Maximum Subarray",
   "src": "LeetCode",
   "diff": "Medium",
   "url": "https://leetcode.com/problems/maximum-subarray/",
   "why": "The O(n^2) version is obvious and too slow. Ask what the growth rate buys you."
  }
 ],
 "F02": [
  {
   "name": "69. Sqrt(x)",
   "src": "LeetCode",
   "diff": "Easy",
   "url": "https://leetcode.com/problems/sqrtx/",
   "why": "Halving the search space: how many halvings before one candidate is left?"
  },
  {
   "name": "50. Pow(x, n)",
   "src": "LeetCode",
   "diff": "Medium",
   "url": "https://leetcode.com/problems/powx-n/",
   "why": "Halving the exponent. Count the multiplications, then check it is log n."
  },
  {
   "name": "Exponentiation",
   "src": "CSES",
   "diff": "Mathematics",
   "url": "https://cses.fi/problemset/task/1095",
   "why": "The same halving, with a modulus and n up to 1e9."
  }
 ],
 "F03": [
  {
   "name": "268. Missing Number",
   "src": "LeetCode",
   "diff": "Easy",
   "url": "https://leetcode.com/problems/missing-number/",
   "why": "Gauss's n(n+1)/2 in one line instead of a scan."
  },
  {
   "name": "Missing Number",
   "src": "CSES",
   "diff": "Introductory Problems",
   "url": "https://cses.fi/problemset/task/1083",
   "why": "The same sum, with n up to 2e5 and a 64-bit answer."
  },
  {
   "name": "Trailing Zeros",
   "src": "CSES",
   "diff": "Introductory Problems",
   "url": "https://cses.fi/problemset/task/1618",
   "why": "A geometric series in disguise: n/5 + n/25 + n/125 + ... Why does it terminate quickly?"
  }
 ],
 "F14": [
  {
   "name": "Bit Strings",
   "src": "CSES",
   "diff": "Introductory Problems",
   "url": "https://cses.fi/problemset/task/1617",
   "why": "2^n mod m: counting strings without listing them."
  },
  {
   "name": "Two Knights",
   "src": "CSES",
   "diff": "Introductory Problems",
   "url": "https://cses.fi/problemset/task/1072",
   "why": "Count the placements, then subtract the attacking ones. Pure counting."
  },
  {
   "name": "62. Unique Paths",
   "src": "LeetCode",
   "diff": "Medium",
   "url": "https://leetcode.com/problems/unique-paths/",
   "why": "A binomial coefficient wearing a grid costume."
  },
  {
   "name": "Binomial Coefficients",
   "src": "CSES",
   "diff": "Mathematics",
   "url": "https://cses.fi/problemset/task/1079",
   "why": "nCk mod p for huge n: counting plus modular arithmetic."
  }
 ],
 "F07": [
  {
   "name": "75. Sort Colors",
   "src": "LeetCode",
   "diff": "Medium",
   "url": "https://leetcode.com/problems/sort-colors/",
   "why": "Dutch flag: write down what the three regions mean before you write the loop."
  },
  {
   "name": "283. Move Zeroes",
   "src": "LeetCode",
   "diff": "Easy",
   "url": "https://leetcode.com/problems/move-zeroes/",
   "why": "State the invariant for the write pointer, then prove the loop keeps it."
  },
  {
   "name": "Increasing Array",
   "src": "CSES",
   "diff": "Introductory Problems",
   "url": "https://cses.fi/problemset/task/1094",
   "why": "A one-line greedy. The invariant is why it is optimal, not the code."
  }
 ],
 "F08": [
  {
   "name": "Tower of Hanoi",
   "src": "CSES",
   "diff": "Introductory Problems",
   "url": "https://cses.fi/problemset/task/2165",
   "why": "Hanoi: the recursion is three lines; the proof is the point."
  },
  {
   "name": "Gray Code",
   "src": "CSES",
   "diff": "Introductory Problems",
   "url": "https://cses.fi/problemset/task/2205",
   "why": "Gray code: build n from n-1 and say why the property survives."
  },
  {
   "name": "21. Merge Two Sorted Lists",
   "src": "LeetCode",
   "diff": "Easy",
   "url": "https://leetcode.com/problems/merge-two-sorted-lists/",
   "why": "Write it recursively and justify it by induction on the total length."
  }
 ],
 "F09": [
  {
   "name": "240. Search a 2D Matrix II",
   "src": "LeetCode",
   "diff": "Medium",
   "url": "https://leetcode.com/problems/search-a-2d-matrix-ii/",
   "why": "Start at a corner: every step deletes a whole row or column. Prove nothing lost."
  },
  {
   "name": "167. Two Sum II - Input Array Is Sorted",
   "src": "LeetCode",
   "diff": "Medium",
   "url": "https://leetcode.com/problems/two-sum-ii-input-array-is-sorted/",
   "why": "Each move discards a row of the pair table. Which row, and why is it safe?"
  },
  {
   "name": "162. Find Peak Element",
   "src": "LeetCode",
   "diff": "Medium",
   "url": "https://leetcode.com/problems/find-peak-element/",
   "why": "Half the array is eliminated with no sortedness at all. Why is that legal?"
  }
 ],
 "F13": [
  {
   "name": "278. First Bad Version",
   "src": "LeetCode",
   "diff": "Easy",
   "url": "https://leetcode.com/problems/first-bad-version/",
   "why": "The cleanest monotone predicate there is: false...false true...true."
  },
  {
   "name": "875. Koko Eating Bananas",
   "src": "LeetCode",
   "diff": "Medium",
   "url": "https://leetcode.com/problems/koko-eating-bananas/",
   "why": "Name the predicate, prove it is monotone, then binary search it."
  },
  {
   "name": "Factory Machines",
   "src": "CSES",
   "diff": "Sorting and Searching",
   "url": "https://cses.fi/problemset/task/1620",
   "why": "Same shape, bigger numbers: is t time enough to make k products?"
  }
 ],
 "F10": [
  {
   "name": "138. Copy List with Random Pointer",
   "src": "LeetCode",
   "diff": "Medium",
   "url": "https://leetcode.com/problems/copy-list-with-random-pointer/",
   "why": "References versus copies. Drawing the arrows is the whole problem."
  },
  {
   "name": "48. Rotate Image",
   "src": "LeetCode",
   "diff": "Medium",
   "url": "https://leetcode.com/problems/rotate-image/",
   "why": "In-place index arithmetic on one contiguous block."
  },
  {
   "name": "73. Set Matrix Zeroes",
   "src": "LeetCode",
   "diff": "Medium",
   "url": "https://leetcode.com/problems/set-matrix-zeroes/",
   "why": "The O(1)-space version forces you to think about what the memory actually holds."
  }
 ],
 "F04": [
  {
   "name": "155. Min Stack",
   "src": "LeetCode",
   "diff": "Medium",
   "url": "https://leetcode.com/problems/min-stack/",
   "why": "O(1) amortised per operation. Account for the worst single push."
  },
  {
   "name": "232. Implement Queue using Stacks",
   "src": "LeetCode",
   "diff": "Easy",
   "url": "https://leetcode.com/problems/implement-queue-using-stacks/",
   "why": "Each element moves between stacks at most once: the classic amortised argument."
  },
  {
   "name": "739. Daily Temperatures",
   "src": "LeetCode",
   "diff": "Medium",
   "url": "https://leetcode.com/problems/daily-temperatures/",
   "why": "Every index is pushed once and popped once, so the nested loop is still O(n)."
  }
 ],
 "F11": [
  {
   "name": "706. Design HashMap",
   "src": "LeetCode",
   "diff": "Easy",
   "url": "https://leetcode.com/problems/design-hashmap/",
   "why": "Build the table yourself: buckets, collisions, resizing."
  },
  {
   "name": "49. Group Anagrams",
   "src": "LeetCode",
   "diff": "Medium",
   "url": "https://leetcode.com/problems/group-anagrams/",
   "why": "Hashing a derived key, and why the key must be canonical."
  },
  {
   "name": "128. Longest Consecutive Sequence",
   "src": "LeetCode",
   "diff": "Medium",
   "url": "https://leetcode.com/problems/longest-consecutive-sequence/",
   "why": "O(n) only if you can argue each element is visited a constant number of times."
  }
 ],
 "F16": [
  {
   "name": "104. Maximum Depth of Binary Tree",
   "src": "LeetCode",
   "diff": "Easy",
   "url": "https://leetcode.com/problems/maximum-depth-of-binary-tree/",
   "why": "Height by definition, in three lines."
  },
  {
   "name": "110. Balanced Binary Tree",
   "src": "LeetCode",
   "diff": "Easy",
   "url": "https://leetcode.com/problems/balanced-binary-tree/",
   "why": "Height and balance in one pass; the anatomy vocabulary pays off here."
  },
  {
   "name": "222. Count Complete Tree Nodes",
   "src": "LeetCode",
   "diff": "Medium",
   "url": "https://leetcode.com/problems/count-complete-tree-nodes/",
   "why": "Uses the shape of a complete tree to beat O(n). Draw it first."
  }
 ],
 "F15": [
  {
   "name": "1971. Find if Path Exists in Graph",
   "src": "LeetCode",
   "diff": "Easy",
   "url": "https://leetcode.com/problems/find-if-path-exists-in-graph/",
   "why": "Build the adjacency list from an edge list, then walk it."
  },
  {
   "name": "Building Roads",
   "src": "CSES",
   "diff": "Graph Algorithms",
   "url": "https://cses.fi/problemset/task/1666",
   "why": "n, m up to 1e5: the representation decides whether you pass."
  },
  {
   "name": "133. Clone Graph",
   "src": "LeetCode",
   "diff": "Medium",
   "url": "https://leetcode.com/problems/clone-graph/",
   "why": "You cannot copy a graph without being clear on what a node and an edge are."
  }
 ],
 "F05": [
  {
   "name": "94. Binary Tree Inorder Traversal",
   "src": "LeetCode",
   "diff": "Easy",
   "url": "https://leetcode.com/problems/binary-tree-inorder-traversal/",
   "why": "Write it recursively, then iteratively with your own stack. Same frames, visible."
  },
  {
   "name": "Creating Strings",
   "src": "CSES",
   "diff": "Introductory Problems",
   "url": "https://cses.fi/problemset/task/1622",
   "why": "Generating strings: the call stack is the partial answer."
  },
  {
   "name": "206. Reverse Linked List",
   "src": "LeetCode",
   "diff": "Easy",
   "url": "https://leetcode.com/problems/reverse-linked-list/",
   "why": "Do the recursive version and say what each frame holds."
  }
 ],
 "F06": [
  {
   "name": "912. Sort an Array",
   "src": "LeetCode",
   "diff": "Medium",
   "url": "https://leetcode.com/problems/sort-an-array/",
   "why": "Write merge sort, draw the recursion tree, count the levels and the work per level."
  },
  {
   "name": "215. Kth Largest Element in an Array",
   "src": "LeetCode",
   "diff": "Medium",
   "url": "https://leetcode.com/problems/kth-largest-element-in-an-array/",
   "why": "Quickselect: T(n) = T(n/2) + n averages to O(n). Why not n log n?"
  },
  {
   "name": "33. Search in Rotated Sorted Array",
   "src": "LeetCode",
   "diff": "Medium",
   "url": "https://leetcode.com/problems/search-in-rotated-sorted-array/",
   "why": "T(n) = T(n/2) + O(1). Name the recurrence before you code."
  }
 ],
 "F12": [
  {
   "name": "Stick Lengths",
   "src": "CSES",
   "diff": "Sorting and Searching",
   "url": "https://cses.fi/problemset/task/1074",
   "why": "Sorting makes the answer obvious: the median. Prove it."
  },
  {
   "name": "Ferris Wheel",
   "src": "CSES",
   "diff": "Sorting and Searching",
   "url": "https://cses.fi/problemset/task/1090",
   "why": "Sort, then two pointers. The sort is the expensive part and it dominates."
  },
  {
   "name": "179. Largest Number",
   "src": "LeetCode",
   "diff": "Medium",
   "url": "https://leetcode.com/problems/largest-number/",
   "why": "A custom comparator, and the proof that it is a valid ordering."
  }
 ],
 "P01": [
  {
   "name": "Sum of Two Values",
   "src": "CSES",
   "diff": "Sorting and Searching",
   "url": "https://cses.fi/problemset/task/1640",
   "why": "Two values summing to x. The map version is one pass."
  },
  {
   "name": "560. Subarray Sum Equals K",
   "src": "LeetCode",
   "diff": "Medium",
   "url": "https://leetcode.com/problems/subarray-sum-equals-k/",
   "why": "Prefix sum counts in a map: the step most people cannot re-derive."
  },
  {
   "name": "Subarray Sums II",
   "src": "CSES",
   "diff": "Sorting and Searching",
   "url": "https://cses.fi/problemset/task/1661",
   "why": "The same counting trick, n up to 2e5."
  },
  {
   "name": "128. Longest Consecutive Sequence",
   "src": "LeetCode",
   "diff": "Medium",
   "url": "https://leetcode.com/problems/longest-consecutive-sequence/",
   "why": "A set turns an O(n log n) sort into O(n)."
  },
  {
   "name": "Collecting Numbers",
   "src": "CSES",
   "diff": "Sorting and Searching",
   "url": "https://cses.fi/problemset/task/2216",
   "why": "Positions in a map, then one scan."
  }
 ],
 "P02": [
  {
   "name": "Apartments",
   "src": "CSES",
   "diff": "Sorting and Searching",
   "url": "https://cses.fi/problemset/task/1084",
   "why": "Sort both sides, then walk them together."
  },
  {
   "name": "15. 3Sum",
   "src": "LeetCode",
   "diff": "Medium",
   "url": "https://leetcode.com/problems/3sum/",
   "why": "Fix one, converge on the rest. The duplicate handling is where people lose it."
  },
  {
   "name": "Sum of Three Values",
   "src": "CSES",
   "diff": "Sorting and Searching",
   "url": "https://cses.fi/problemset/task/1641",
   "why": "Three values: the same converging pair inside a loop."
  },
  {
   "name": "11. Container With Most Water",
   "src": "LeetCode",
   "diff": "Medium",
   "url": "https://leetcode.com/problems/container-with-most-water/",
   "why": "The move rule needs a proof, not a feeling."
  },
  {
   "name": "42. Trapping Rain Water",
   "src": "LeetCode",
   "diff": "Hard",
   "url": "https://leetcode.com/problems/trapping-rain-water/",
   "why": "Two pointers with an invariant about the taller wall."
  }
 ],
 "P03": [
  {
   "name": "26. Remove Duplicates from Sorted Array",
   "src": "LeetCode",
   "diff": "Easy",
   "url": "https://leetcode.com/problems/remove-duplicates-from-sorted-array/",
   "why": "Read and write pointer; state what is left of write."
  },
  {
   "name": "142. Linked List Cycle II",
   "src": "LeetCode",
   "diff": "Medium",
   "url": "https://leetcode.com/problems/linked-list-cycle-ii/",
   "why": "Fast and slow, then the entry point. Derive the meeting distance."
  },
  {
   "name": "143. Reorder List",
   "src": "LeetCode",
   "diff": "Medium",
   "url": "https://leetcode.com/problems/reorder-list/",
   "why": "Find the middle, reverse, merge: three same-direction passes."
  },
  {
   "name": "Increasing Array",
   "src": "CSES",
   "diff": "Introductory Problems",
   "url": "https://cses.fi/problemset/task/1094",
   "why": "One pass carrying a running maximum."
  }
 ],
 "P04": [
  {
   "name": "3. Longest Substring Without Repeating Characters",
   "src": "LeetCode",
   "diff": "Medium",
   "url": "https://leetcode.com/problems/longest-substring-without-repeating-characters/",
   "why": "The window shrinks only from the left. Why is that enough?"
  },
  {
   "name": "209. Minimum Size Subarray Sum",
   "src": "LeetCode",
   "diff": "Medium",
   "url": "https://leetcode.com/problems/minimum-size-subarray-sum/",
   "why": "Positive numbers make the window monotone; note where that is used."
  },
  {
   "name": "Playlist",
   "src": "CSES",
   "diff": "Sorting and Searching",
   "url": "https://cses.fi/problemset/task/1141",
   "why": "Longest distinct-value window, n up to 2e5."
  },
  {
   "name": "567. Permutation in String",
   "src": "LeetCode",
   "diff": "Medium",
   "url": "https://leetcode.com/problems/permutation-in-string/",
   "why": "Fixed-width window with a count array."
  },
  {
   "name": "76. Minimum Window Substring",
   "src": "LeetCode",
   "diff": "Hard",
   "url": "https://leetcode.com/problems/minimum-window-substring/",
   "why": "The hard one: counts, a match counter, and a careful shrink."
  },
  {
   "name": "Sliding Window Distinct Values",
   "src": "CSES",
   "diff": "Sliding Window Problems",
   "url": "https://cses.fi/problemset/task/3222",
   "why": "Distinct values in every window of length k."
  }
 ],
 "P05": [
  {
   "name": "704. Binary Search",
   "src": "LeetCode",
   "diff": "Easy",
   "url": "https://leetcode.com/problems/binary-search/",
   "why": "Pick one template and never change it again."
  },
  {
   "name": "34. Find First and Last Position of Element in Sorted Array",
   "src": "LeetCode",
   "diff": "Medium",
   "url": "https://leetcode.com/problems/find-first-and-last-position-of-element-in-sorted-array/",
   "why": "Lower and upper bound as the same loop with one comparison changed."
  },
  {
   "name": "33. Search in Rotated Sorted Array",
   "src": "LeetCode",
   "diff": "Medium",
   "url": "https://leetcode.com/problems/search-in-rotated-sorted-array/",
   "why": "Which half is sorted? That is the whole problem."
  },
  {
   "name": "153. Find Minimum in Rotated Sorted Array",
   "src": "LeetCode",
   "diff": "Medium",
   "url": "https://leetcode.com/problems/find-minimum-in-rotated-sorted-array/",
   "why": "Compare with the right end, not the left. Work out why."
  },
  {
   "name": "4. Median of Two Sorted Arrays",
   "src": "LeetCode",
   "diff": "Hard",
   "url": "https://leetcode.com/problems/median-of-two-sorted-arrays/",
   "why": "Binary search on the partition, not on the value."
  }
 ],
 "P06": [
  {
   "name": "875. Koko Eating Bananas",
   "src": "LeetCode",
   "diff": "Medium",
   "url": "https://leetcode.com/problems/koko-eating-bananas/",
   "why": "The template: predicate, monotone, smallest true."
  },
  {
   "name": "1011. Capacity To Ship Packages Within D Days",
   "src": "LeetCode",
   "diff": "Medium",
   "url": "https://leetcode.com/problems/capacity-to-ship-packages-within-d-days/",
   "why": "Same shape; the bounds are the interesting part."
  },
  {
   "name": "Array Division",
   "src": "CSES",
   "diff": "Sorting and Searching",
   "url": "https://cses.fi/problemset/task/1085",
   "why": "Array division: minimise the largest piece."
  },
  {
   "name": "Factory Machines",
   "src": "CSES",
   "diff": "Sorting and Searching",
   "url": "https://cses.fi/problemset/task/1620",
   "why": "Factory machines: the answer space is time, not an index."
  },
  {
   "name": "410. Split Array Largest Sum",
   "src": "LeetCode",
   "diff": "Hard",
   "url": "https://leetcode.com/problems/split-array-largest-sum/",
   "why": "Recognise it as the same problem in different clothes."
  },
  {
   "name": "1482. Minimum Number of Days to Make m Bouquets",
   "src": "LeetCode",
   "diff": "Medium",
   "url": "https://leetcode.com/problems/minimum-number-of-days-to-make-m-bouquets/",
   "why": "Predicate on days, greedy check inside."
  }
 ],
 "P07": [
  {
   "name": "20. Valid Parentheses",
   "src": "LeetCode",
   "diff": "Easy",
   "url": "https://leetcode.com/problems/valid-parentheses/",
   "why": "The stack as a memory of what is still open."
  },
  {
   "name": "739. Daily Temperatures",
   "src": "LeetCode",
   "diff": "Medium",
   "url": "https://leetcode.com/problems/daily-temperatures/",
   "why": "Next greater element. Say what the stack holds at all times."
  },
  {
   "name": "Nearest Smaller Values",
   "src": "CSES",
   "diff": "Sorting and Searching",
   "url": "https://cses.fi/problemset/task/1645",
   "why": "Nearest smaller values, n up to 2e5."
  },
  {
   "name": "150. Evaluate Reverse Polish Notation",
   "src": "LeetCode",
   "diff": "Medium",
   "url": "https://leetcode.com/problems/evaluate-reverse-polish-notation/",
   "why": "A stack machine, and why RPN needs no brackets."
  },
  {
   "name": "84. Largest Rectangle in Histogram",
   "src": "LeetCode",
   "diff": "Hard",
   "url": "https://leetcode.com/problems/largest-rectangle-in-histogram/",
   "why": "The hard one: each bar's span comes from the pops."
  },
  {
   "name": "907. Sum of Subarray Minimums",
   "src": "LeetCode",
   "diff": "Medium",
   "url": "https://leetcode.com/problems/sum-of-subarray-minimums/",
   "why": "Counting the subarrays each element wins, via the same stack."
  }
 ],
 "P08": [
  {
   "name": "206. Reverse Linked List",
   "src": "LeetCode",
   "diff": "Easy",
   "url": "https://leetcode.com/problems/reverse-linked-list/",
   "why": "Three pointers. Draw them before coding."
  },
  {
   "name": "19. Remove Nth Node From End of List",
   "src": "LeetCode",
   "diff": "Medium",
   "url": "https://leetcode.com/problems/remove-nth-node-from-end-of-list/",
   "why": "The dummy head exists so the first node is not special."
  },
  {
   "name": "2. Add Two Numbers",
   "src": "LeetCode",
   "diff": "Medium",
   "url": "https://leetcode.com/problems/add-two-numbers/",
   "why": "Carry handling and the final node."
  },
  {
   "name": "138. Copy List with Random Pointer",
   "src": "LeetCode",
   "diff": "Medium",
   "url": "https://leetcode.com/problems/copy-list-with-random-pointer/",
   "why": "Interleave-and-split, or a map. Both are worth writing."
  },
  {
   "name": "146. LRU Cache",
   "src": "LeetCode",
   "diff": "Medium",
   "url": "https://leetcode.com/problems/lru-cache/",
   "why": "Doubly linked list plus map. Standard interview build."
  }
 ],
 "P09": [
  {
   "name": "102. Binary Tree Level Order Traversal",
   "src": "LeetCode",
   "diff": "Medium",
   "url": "https://leetcode.com/problems/binary-tree-level-order-traversal/",
   "why": "BFS with an explicit level boundary."
  },
  {
   "name": "98. Validate Binary Search Tree",
   "src": "LeetCode",
   "diff": "Medium",
   "url": "https://leetcode.com/problems/validate-binary-search-tree/",
   "why": "Carry bounds down, not a parent comparison."
  },
  {
   "name": "Subordinates",
   "src": "CSES",
   "diff": "Tree Algorithms",
   "url": "https://cses.fi/problemset/task/1674",
   "why": "Subtree sizes: DFS returning a value up."
  },
  {
   "name": "236. Lowest Common Ancestor of a Binary Tree",
   "src": "LeetCode",
   "diff": "Medium",
   "url": "https://leetcode.com/problems/lowest-common-ancestor-of-a-binary-tree/",
   "why": "The post-order argument: what does a non-null return mean?"
  },
  {
   "name": "124. Binary Tree Maximum Path Sum",
   "src": "LeetCode",
   "diff": "Hard",
   "url": "https://leetcode.com/problems/binary-tree-maximum-path-sum/",
   "why": "Return one thing, record another. Name both."
  },
  {
   "name": "297. Serialize and Deserialize Binary Tree",
   "src": "LeetCode",
   "diff": "Hard",
   "url": "https://leetcode.com/problems/serialize-and-deserialize-binary-tree/",
   "why": "Traversal order plus null markers determines the tree."
  }
 ],
 "P10": [
  {
   "name": "1046. Last Stone Weight",
   "src": "LeetCode",
   "diff": "Easy",
   "url": "https://leetcode.com/problems/last-stone-weight/",
   "why": "A heap where the array would be O(n^2)."
  },
  {
   "name": "973. K Closest Points to Origin",
   "src": "LeetCode",
   "diff": "Medium",
   "url": "https://leetcode.com/problems/k-closest-points-to-origin/",
   "why": "Size-k heap: why keep the *largest* at the top?"
  },
  {
   "name": "347. Top K Frequent Elements",
   "src": "LeetCode",
   "diff": "Medium",
   "url": "https://leetcode.com/problems/top-k-frequent-elements/",
   "why": "Count, then heap or bucket. Compare the two costs."
  },
  {
   "name": "Room Allocation",
   "src": "CSES",
   "diff": "Sorting and Searching",
   "url": "https://cses.fi/problemset/task/1164",
   "why": "Room allocation: a heap of end times."
  },
  {
   "name": "295. Find Median from Data Stream",
   "src": "LeetCode",
   "diff": "Hard",
   "url": "https://leetcode.com/problems/find-median-from-data-stream/",
   "why": "Two heaps and the balance invariant."
  },
  {
   "name": "Sliding Window Median",
   "src": "CSES",
   "diff": "Sliding Window Problems",
   "url": "https://cses.fi/problemset/task/1076",
   "why": "Sliding window median: the same two heaps, with removals."
  }
 ],
 "P11": [
  {
   "name": "Permutations",
   "src": "CSES",
   "diff": "Introductory Problems",
   "url": "https://cses.fi/problemset/task/1070",
   "why": "Permutations: the plainest backtracking skeleton."
  },
  {
   "name": "78. Subsets",
   "src": "LeetCode",
   "diff": "Medium",
   "url": "https://leetcode.com/problems/subsets/",
   "why": "Include/exclude, and the 2^n count."
  },
  {
   "name": "39. Combination Sum",
   "src": "LeetCode",
   "diff": "Medium",
   "url": "https://leetcode.com/problems/combination-sum/",
   "why": "Where the loop starts is what stops duplicates."
  },
  {
   "name": "Apple Division",
   "src": "CSES",
   "diff": "Introductory Problems",
   "url": "https://cses.fi/problemset/task/1623",
   "why": "Apple division: 2^n split, n <= 20."
  },
  {
   "name": "79. Word Search",
   "src": "LeetCode",
   "diff": "Medium",
   "url": "https://leetcode.com/problems/word-search/",
   "why": "Grid backtracking with mark and unmark."
  },
  {
   "name": "Chessboard and Queens",
   "src": "CSES",
   "diff": "Introductory Problems",
   "url": "https://cses.fi/problemset/task/1624",
   "why": "Eight queens with pruning. Count the nodes you avoided."
  },
  {
   "name": "131. Palindrome Partitioning",
   "src": "LeetCode",
   "diff": "Medium",
   "url": "https://leetcode.com/problems/palindrome-partitioning/",
   "why": "Backtracking plus a palindrome check you can precompute."
  }
 ],
 "P12": [
  {
   "name": "Counting Rooms",
   "src": "CSES",
   "diff": "Graph Algorithms",
   "url": "https://cses.fi/problemset/task/1192",
   "why": "Counting rooms: flood fill on a grid."
  },
  {
   "name": "200. Number of Islands",
   "src": "LeetCode",
   "diff": "Medium",
   "url": "https://leetcode.com/problems/number-of-islands/",
   "why": "The same flood fill, interview phrasing."
  },
  {
   "name": "Labyrinth",
   "src": "CSES",
   "diff": "Graph Algorithms",
   "url": "https://cses.fi/problemset/task/1193",
   "why": "Labyrinth: BFS plus reconstructing the path."
  },
  {
   "name": "994. Rotting Oranges",
   "src": "LeetCode",
   "diff": "Medium",
   "url": "https://leetcode.com/problems/rotting-oranges/",
   "why": "Multi-source BFS: seed the queue with every source."
  },
  {
   "name": "Building Teams",
   "src": "CSES",
   "diff": "Graph Algorithms",
   "url": "https://cses.fi/problemset/task/1668",
   "why": "Bipartite check by two-colouring."
  },
  {
   "name": "127. Word Ladder",
   "src": "LeetCode",
   "diff": "Hard",
   "url": "https://leetcode.com/problems/word-ladder/",
   "why": "BFS over an implicit graph you never build."
  },
  {
   "name": "Message Route",
   "src": "CSES",
   "diff": "Graph Algorithms",
   "url": "https://cses.fi/problemset/task/1667",
   "why": "Message route: shortest path plus parent pointers."
  }
 ],
 "P13": [
  {
   "name": "207. Course Schedule",
   "src": "LeetCode",
   "diff": "Medium",
   "url": "https://leetcode.com/problems/course-schedule/",
   "why": "Cycle detection as a failed topological order."
  },
  {
   "name": "Course Schedule",
   "src": "CSES",
   "diff": "Graph Algorithms",
   "url": "https://cses.fi/problemset/task/1679",
   "why": "Course schedule, CSES version: print an order or report a cycle."
  },
  {
   "name": "210. Course Schedule II",
   "src": "LeetCode",
   "diff": "Medium",
   "url": "https://leetcode.com/problems/course-schedule-ii/",
   "why": "Kahn's algorithm with in-degrees."
  },
  {
   "name": "Longest Flight Route",
   "src": "CSES",
   "diff": "Graph Algorithms",
   "url": "https://cses.fi/problemset/task/1680",
   "why": "Longest flight route: DP along the topological order."
  },
  {
   "name": "Game Routes",
   "src": "CSES",
   "diff": "Graph Algorithms",
   "url": "https://cses.fi/problemset/task/1681",
   "why": "Game routes: counting paths in a DAG."
  },
  {
   "name": "2192. All Ancestors of a Node in a Directed Acyclic Graph",
   "src": "LeetCode",
   "diff": "Medium",
   "url": "https://leetcode.com/problems/all-ancestors-of-a-node-in-a-directed-acyclic-graph/",
   "why": "Propagating sets along the order."
  }
 ],
 "P14": [
  {
   "name": "Shortest Routes I",
   "src": "CSES",
   "diff": "Graph Algorithms",
   "url": "https://cses.fi/problemset/task/1671",
   "why": "Shortest routes I: plain Dijkstra with a heap."
  },
  {
   "name": "743. Network Delay Time",
   "src": "LeetCode",
   "diff": "Medium",
   "url": "https://leetcode.com/problems/network-delay-time/",
   "why": "Same algorithm, interview phrasing."
  },
  {
   "name": "1631. Path With Minimum Effort",
   "src": "LeetCode",
   "diff": "Medium",
   "url": "https://leetcode.com/problems/path-with-minimum-effort/",
   "why": "Dijkstra where the edge cost is a maximum, not a sum."
  },
  {
   "name": "Flight Discount",
   "src": "CSES",
   "diff": "Graph Algorithms",
   "url": "https://cses.fi/problemset/task/1195",
   "why": "Flight discount: two-layer state graph."
  },
  {
   "name": "778. Swim in Rising Water",
   "src": "LeetCode",
   "diff": "Hard",
   "url": "https://leetcode.com/problems/swim-in-rising-water/",
   "why": "Minimise the largest edge on a path."
  },
  {
   "name": "Flight Routes",
   "src": "CSES",
   "diff": "Graph Algorithms",
   "url": "https://cses.fi/problemset/task/1196",
   "why": "k shortest routes: the priority queue relaxed."
  }
 ],
 "P15": [
  {
   "name": "547. Number of Provinces",
   "src": "LeetCode",
   "diff": "Medium",
   "url": "https://leetcode.com/problems/number-of-provinces/",
   "why": "Union-find where DFS would also do. Write both."
  },
  {
   "name": "Road Construction",
   "src": "CSES",
   "diff": "Graph Algorithms",
   "url": "https://cses.fi/problemset/task/1676",
   "why": "Road construction: components and the largest one, online."
  },
  {
   "name": "684. Redundant Connection",
   "src": "LeetCode",
   "diff": "Medium",
   "url": "https://leetcode.com/problems/redundant-connection/",
   "why": "The first edge that closes a cycle."
  },
  {
   "name": "721. Accounts Merge",
   "src": "LeetCode",
   "diff": "Medium",
   "url": "https://leetcode.com/problems/accounts-merge/",
   "why": "Union-find over strings; the mapping is half the work."
  },
  {
   "name": "990. Satisfiability of Equality Equations",
   "src": "LeetCode",
   "diff": "Medium",
   "url": "https://leetcode.com/problems/satisfiability-of-equality-equations/",
   "why": "Process the equalities first. Why that order?"
  },
  {
   "name": "947. Most Stones Removed with Same Row or Column",
   "src": "LeetCode",
   "diff": "Medium",
   "url": "https://leetcode.com/problems/most-stones-removed-with-same-row-or-column/",
   "why": "Modelling: what exactly is a node here?"
  }
 ],
 "P16": [
  {
   "name": "70. Climbing Stairs",
   "src": "LeetCode",
   "diff": "Easy",
   "url": "https://leetcode.com/problems/climbing-stairs/",
   "why": "The smallest recurrence there is. Say the state out loud."
  },
  {
   "name": "Dice Combinations",
   "src": "CSES",
   "diff": "Dynamic Programming",
   "url": "https://cses.fi/problemset/task/1633",
   "why": "Dice combinations: counting, ordered."
  },
  {
   "name": "322. Coin Change",
   "src": "LeetCode",
   "diff": "Medium",
   "url": "https://leetcode.com/problems/coin-change/",
   "why": "Minimising; note where the loop order stops double counting."
  },
  {
   "name": "Coin Combinations I",
   "src": "CSES",
   "diff": "Dynamic Programming",
   "url": "https://cses.fi/problemset/task/1635",
   "why": "Coin combinations I and II: ordered versus unordered, same table."
  },
  {
   "name": "198. House Robber",
   "src": "LeetCode",
   "diff": "Medium",
   "url": "https://leetcode.com/problems/house-robber/",
   "why": "Two states per index, or one with a rolling pair."
  },
  {
   "name": "Book Shop",
   "src": "CSES",
   "diff": "Dynamic Programming",
   "url": "https://cses.fi/problemset/task/1158",
   "why": "Book shop: 0/1 knapsack in disguise."
  },
  {
   "name": "300. Longest Increasing Subsequence",
   "src": "LeetCode",
   "diff": "Medium",
   "url": "https://leetcode.com/problems/longest-increasing-subsequence/",
   "why": "Write O(n^2), then the patience/binary-search version."
  },
  {
   "name": "72. Edit Distance",
   "src": "LeetCode",
   "diff": "Medium",
   "url": "https://leetcode.com/problems/edit-distance/",
   "why": "Two-dimensional state; draw the three arrows into a cell."
  },
  {
   "name": "416. Partition Equal Subset Sum",
   "src": "LeetCode",
   "diff": "Medium",
   "url": "https://leetcode.com/problems/partition-equal-subset-sum/",
   "why": "Subset sum as a boolean table, then as a bitset."
  }
 ],
 "P17": [
  {
   "name": "Movie Festival",
   "src": "CSES",
   "diff": "Sorting and Searching",
   "url": "https://cses.fi/problemset/task/1629",
   "why": "Movie festival: sort by end time, and prove the exchange argument."
  },
  {
   "name": "56. Merge Intervals",
   "src": "LeetCode",
   "diff": "Medium",
   "url": "https://leetcode.com/problems/merge-intervals/",
   "why": "Sort by start, then one sweep."
  },
  {
   "name": "57. Insert Interval",
   "src": "LeetCode",
   "diff": "Medium",
   "url": "https://leetcode.com/problems/insert-interval/",
   "why": "No sort needed; three phases."
  },
  {
   "name": "435. Non-overlapping Intervals",
   "src": "LeetCode",
   "diff": "Medium",
   "url": "https://leetcode.com/problems/non-overlapping-intervals/",
   "why": "Same greedy as the movie festival, complement phrasing."
  },
  {
   "name": "Restaurant Customers",
   "src": "CSES",
   "diff": "Sorting and Searching",
   "url": "https://cses.fi/problemset/task/1619",
   "why": "Restaurant customers: the +1/-1 sweep."
  },
  {
   "name": "452. Minimum Number of Arrows to Burst Balloons",
   "src": "LeetCode",
   "diff": "Medium",
   "url": "https://leetcode.com/problems/minimum-number-of-arrows-to-burst-balloons/",
   "why": "Greedy on the end point again."
  },
  {
   "name": "Tasks and Deadlines",
   "src": "CSES",
   "diff": "Sorting and Searching",
   "url": "https://cses.fi/problemset/task/1630",
   "why": "Tasks and deadlines: an exchange argument that is not about intervals."
  }
 ],
 "P18": [
  {
   "name": "Static Range Sum Queries",
   "src": "CSES",
   "diff": "Range Queries",
   "url": "https://cses.fi/problemset/task/1646",
   "why": "Static range sums: the definition of a prefix array."
  },
  {
   "name": "724. Find Pivot Index",
   "src": "LeetCode",
   "diff": "Easy",
   "url": "https://leetcode.com/problems/find-pivot-index/",
   "why": "Prefix and suffix in one pass."
  },
  {
   "name": "Subarray Sums I",
   "src": "CSES",
   "diff": "Sorting and Searching",
   "url": "https://cses.fi/problemset/task/1660",
   "why": "Subarray sums I: positive values, so a window also works. Do both."
  },
  {
   "name": "974. Subarray Sums Divisible by K",
   "src": "LeetCode",
   "diff": "Medium",
   "url": "https://leetcode.com/problems/subarray-sums-divisible-by-k/",
   "why": "Prefix sums modulo k, counted in a map. Mind the negatives."
  },
  {
   "name": "Subarray Divisibility",
   "src": "CSES",
   "diff": "Sorting and Searching",
   "url": "https://cses.fi/problemset/task/1662",
   "why": "The same, CSES sizing."
  },
  {
   "name": "1109. Corporate Flight Bookings",
   "src": "LeetCode",
   "diff": "Medium",
   "url": "https://leetcode.com/problems/corporate-flight-bookings/",
   "why": "A difference array: the point of the whole topic."
  },
  {
   "name": "Forest Queries",
   "src": "CSES",
   "diff": "Range Queries",
   "url": "https://cses.fi/problemset/task/1652",
   "why": "Forest queries: 2D prefix sums, inclusion-exclusion."
  },
  {
   "name": "304. Range Sum Query 2D - Immutable",
   "src": "LeetCode",
   "diff": "Medium",
   "url": "https://leetcode.com/problems/range-sum-query-2d-immutable/",
   "why": "The same rectangle formula, interview phrasing."
  }
 ],
 "P19": [
  {
   "name": "Sliding Window Minimum",
   "src": "CSES",
   "diff": "Sliding Window Problems",
   "url": "https://cses.fi/problemset/task/3221",
   "why": "Sliding window minimum: the deque, bare."
  },
  {
   "name": "239. Sliding Window Maximum",
   "src": "LeetCode",
   "diff": "Hard",
   "url": "https://leetcode.com/problems/sliding-window-maximum/",
   "why": "Same thing. Say what the deque holds and why it is sorted."
  },
  {
   "name": "1438. Longest Continuous Subarray With Absolute Diff Less Than or Equal to Limit",
   "src": "LeetCode",
   "diff": "Medium",
   "url": "https://leetcode.com/problems/longest-continuous-subarray-with-absolute-diff-less-than-or-equal-to-limit/",
   "why": "Two deques, max and min, inside one window."
  },
  {
   "name": "1696. Jump Game VI",
   "src": "LeetCode",
   "diff": "Medium",
   "url": "https://leetcode.com/problems/jump-game-vi/",
   "why": "DP where the transition is a window maximum."
  },
  {
   "name": "862. Shortest Subarray with Sum at Least K",
   "src": "LeetCode",
   "diff": "Hard",
   "url": "https://leetcode.com/problems/shortest-subarray-with-sum-at-least-k/",
   "why": "Negatives break the window; the deque over prefix sums saves it."
  },
  {
   "name": "1425. Constrained Subsequence Sum",
   "src": "LeetCode",
   "diff": "Hard",
   "url": "https://leetcode.com/problems/constrained-subsequence-sum/",
   "why": "The same trick, one level more abstract."
  }
 ],
 "P20": [
  {
   "name": "Dynamic Range Sum Queries",
   "src": "CSES",
   "diff": "Range Queries",
   "url": "https://cses.fi/problemset/task/1648",
   "why": "Dynamic range sums: point update, prefix query. The BIT's home problem."
  },
  {
   "name": "307. Range Sum Query - Mutable",
   "src": "LeetCode",
   "diff": "Medium",
   "url": "https://leetcode.com/problems/range-sum-query-mutable/",
   "why": "Same, interview phrasing. A segment tree also works; compare the code."
  },
  {
   "name": "Range Update Queries",
   "src": "CSES",
   "diff": "Range Queries",
   "url": "https://cses.fi/problemset/task/1651",
   "why": "Range update, point query: the difference-array BIT."
  },
  {
   "name": "315. Count of Smaller Numbers After Self",
   "src": "LeetCode",
   "diff": "Hard",
   "url": "https://leetcode.com/problems/count-of-smaller-numbers-after-self/",
   "why": "Counting inversions with a BIT over values."
  },
  {
   "name": "Nested Ranges Count",
   "src": "CSES",
   "diff": "Sorting and Searching",
   "url": "https://cses.fi/problemset/task/2169",
   "why": "Nested ranges count: sort, then count with a BIT."
  },
  {
   "name": "493. Reverse Pairs",
   "src": "LeetCode",
   "diff": "Hard",
   "url": "https://leetcode.com/problems/reverse-pairs/",
   "why": "Inversions with a twist in the comparison."
  },
  {
   "name": "Salary Queries",
   "src": "CSES",
   "diff": "Range Queries",
   "url": "https://cses.fi/problemset/task/1144",
   "why": "Salary queries: values are huge, so compress them first."
  }
 ],
 "P21": [
  {
   "name": "Dynamic Range Minimum Queries",
   "src": "CSES",
   "diff": "Range Queries",
   "url": "https://cses.fi/problemset/task/1649",
   "why": "Dynamic range minimum: point update, range query."
  },
  {
   "name": "Subarray Sum Queries",
   "src": "CSES",
   "diff": "Range Queries",
   "url": "https://cses.fi/problemset/task/1190",
   "why": "Subarray sum queries: a node stores four numbers, not one. Derive the merge."
  },
  {
   "name": "Range Update Queries",
   "src": "CSES",
   "diff": "Range Queries",
   "url": "https://cses.fi/problemset/task/1651",
   "why": "Range update queries, the segment tree way."
  },
  {
   "name": "Range Updates and Sums",
   "src": "CSES",
   "diff": "Range Queries",
   "url": "https://cses.fi/problemset/task/1735",
   "why": "Range updates and sums: two lazy tags that must compose. The real test."
  },
  {
   "name": "732. My Calendar III",
   "src": "LeetCode",
   "diff": "Hard",
   "url": "https://leetcode.com/problems/my-calendar-iii/",
   "why": "Lazy or coordinate-compressed counting."
  },
  {
   "name": "Polynomial Queries",
   "src": "CSES",
   "diff": "Range Queries",
   "url": "https://cses.fi/problemset/task/1736",
   "why": "Polynomial queries: an arithmetic progression as a lazy tag."
  },
  {
   "name": "699. Falling Squares",
   "src": "LeetCode",
   "diff": "Hard",
   "url": "https://leetcode.com/problems/falling-squares/",
   "why": "Range assign and range max; think about what the tag means."
  }
 ],
 "P22": [
  {
   "name": "Company Queries I",
   "src": "CSES",
   "diff": "Tree Algorithms",
   "url": "https://cses.fi/problemset/task/1687",
   "why": "Company queries I: the jump table, nothing else."
  },
  {
   "name": "1483. Kth Ancestor of a Tree Node",
   "src": "LeetCode",
   "diff": "Hard",
   "url": "https://leetcode.com/problems/kth-ancestor-of-a-tree-node/",
   "why": "The same table, interview phrasing."
  },
  {
   "name": "Company Queries II",
   "src": "CSES",
   "diff": "Tree Algorithms",
   "url": "https://cses.fi/problemset/task/1688",
   "why": "Company queries II: the LCA itself."
  },
  {
   "name": "Distance Queries",
   "src": "CSES",
   "diff": "Tree Algorithms",
   "url": "https://cses.fi/problemset/task/1135",
   "why": "Distance queries: depth plus LCA."
  },
  {
   "name": "Planets Queries I",
   "src": "CSES",
   "diff": "Graph Algorithms",
   "url": "https://cses.fi/problemset/task/1750",
   "why": "Planets queries I: binary lifting on a functional graph."
  },
  {
   "name": "Counting Paths",
   "src": "CSES",
   "diff": "Tree Algorithms",
   "url": "https://cses.fi/problemset/task/1136",
   "why": "Counting paths: LCA plus a difference array on the tree."
  }
 ],
 "P23": [
  {
   "name": "Subordinates",
   "src": "CSES",
   "diff": "Tree Algorithms",
   "url": "https://cses.fi/problemset/task/1674",
   "why": "Subordinates: the simplest upward DP."
  },
  {
   "name": "543. Diameter of Binary Tree",
   "src": "LeetCode",
   "diff": "Easy",
   "url": "https://leetcode.com/problems/diameter-of-binary-tree/",
   "why": "Return one value, record another."
  },
  {
   "name": "Tree Diameter",
   "src": "CSES",
   "diff": "Tree Algorithms",
   "url": "https://cses.fi/problemset/task/1131",
   "why": "Tree diameter on a general tree: two DFS, or one DP."
  },
  {
   "name": "337. House Robber III",
   "src": "LeetCode",
   "diff": "Medium",
   "url": "https://leetcode.com/problems/house-robber-iii/",
   "why": "Two states per node."
  },
  {
   "name": "Tree Matching",
   "src": "CSES",
   "diff": "Tree Algorithms",
   "url": "https://cses.fi/problemset/task/1130",
   "why": "Tree matching: include/exclude the edge to the parent."
  },
  {
   "name": "Tree Distances I",
   "src": "CSES",
   "diff": "Tree Algorithms",
   "url": "https://cses.fi/problemset/task/1132",
   "why": "Tree distances I: the rerooting warm-up."
  },
  {
   "name": "Tree Distances II",
   "src": "CSES",
   "diff": "Tree Algorithms",
   "url": "https://cses.fi/problemset/task/1133",
   "why": "Tree distances II: full rerooting. Derive the parent's contribution."
  },
  {
   "name": "834. Sum of Distances in Tree",
   "src": "LeetCode",
   "diff": "Hard",
   "url": "https://leetcode.com/problems/sum-of-distances-in-tree/",
   "why": "The same rerooting, interview phrasing."
  }
 ],
 "P24": [
  {
   "name": "78. Subsets",
   "src": "LeetCode",
   "diff": "Medium",
   "url": "https://leetcode.com/problems/subsets/",
   "why": "Iterate subsets as integers first; everything else builds on that."
  },
  {
   "name": "Elevator Rides",
   "src": "CSES",
   "diff": "Dynamic Programming",
   "url": "https://cses.fi/problemset/task/1653",
   "why": "Elevator rides: classic dp[mask] with two fields."
  },
  {
   "name": "698. Partition to K Equal Sum Subsets",
   "src": "LeetCode",
   "diff": "Medium",
   "url": "https://leetcode.com/problems/partition-to-k-equal-sum-subsets/",
   "why": "Bitmask over used items, with memo."
  },
  {
   "name": "Hamiltonian Flights",
   "src": "CSES",
   "diff": "Graph Algorithms",
   "url": "https://cses.fi/problemset/task/1690",
   "why": "Hamiltonian flights: dp[mask][last], the TSP shape."
  },
  {
   "name": "847. Shortest Path Visiting All Nodes",
   "src": "LeetCode",
   "diff": "Hard",
   "url": "https://leetcode.com/problems/shortest-path-visiting-all-nodes/",
   "why": "TSP as BFS over (mask, node)."
  },
  {
   "name": "Counting Tilings",
   "src": "CSES",
   "diff": "Dynamic Programming",
   "url": "https://cses.fi/problemset/task/2181",
   "why": "Counting tilings: broken-profile DP, the next level up."
  },
  {
   "name": "1434. Number of Ways to Wear Different Hats to Each Other",
   "src": "LeetCode",
   "diff": "Hard",
   "url": "https://leetcode.com/problems/number-of-ways-to-wear-different-hats-to-each-other/",
   "why": "Choose which side to put in the mask. That choice is the problem."
  }
 ],
 "P25": [
  {
   "name": "Removal Game",
   "src": "CSES",
   "diff": "Dynamic Programming",
   "url": "https://cses.fi/problemset/task/1097",
   "why": "Removal game: two players, one interval, one table."
  },
  {
   "name": "516. Longest Palindromic Subsequence",
   "src": "LeetCode",
   "diff": "Medium",
   "url": "https://leetcode.com/problems/longest-palindromic-subsequence/",
   "why": "Interval DP by length; watch the fill order."
  },
  {
   "name": "1547. Minimum Cost to Cut a Stick",
   "src": "LeetCode",
   "diff": "Hard",
   "url": "https://leetcode.com/problems/minimum-cost-to-cut-a-stick/",
   "why": "Add the endpoints, then it is textbook."
  },
  {
   "name": "312. Burst Balloons",
   "src": "LeetCode",
   "diff": "Hard",
   "url": "https://leetcode.com/problems/burst-balloons/",
   "why": "Choose the *last* balloon in the interval, not the first. Say why."
  },
  {
   "name": "1690. Stone Game VII",
   "src": "LeetCode",
   "diff": "Medium",
   "url": "https://leetcode.com/problems/stone-game-vii/",
   "why": "Margin form: one table instead of two."
  },
  {
   "name": "Empty String",
   "src": "CSES",
   "diff": "Counting Problems",
   "url": "https://cses.fi/problemset/task/1080",
   "why": "Empty string: interval DP with counting."
  },
  {
   "name": "664. Strange Printer",
   "src": "LeetCode",
   "diff": "Hard",
   "url": "https://leetcode.com/problems/strange-printer/",
   "why": "Harder merge rule; derive it on paper first."
  }
 ],
 "P26": [
  {
   "name": "Road Reparation",
   "src": "CSES",
   "diff": "Graph Algorithms",
   "url": "https://cses.fi/problemset/task/1675",
   "why": "Road reparation: Kruskal, straight."
  },
  {
   "name": "1584. Min Cost to Connect All Points",
   "src": "LeetCode",
   "diff": "Medium",
   "url": "https://leetcode.com/problems/min-cost-to-connect-all-points/",
   "why": "Dense graph, so Prim without a heap is competitive. Compare."
  },
  {
   "name": "1489. Find Critical and Pseudo-Critical Edges in Minimum Spanning Tree",
   "src": "LeetCode",
   "diff": "Hard",
   "url": "https://leetcode.com/problems/find-critical-and-pseudo-critical-edges-in-minimum-spanning-tree/",
   "why": "Forces you to actually use the cut and cycle properties."
  },
  {
   "name": "Road Construction",
   "src": "CSES",
   "diff": "Graph Algorithms",
   "url": "https://cses.fi/problemset/task/1676",
   "why": "Road construction: union-find incrementally, no MST needed. Know the difference."
  }
 ],
 "P27": [
  {
   "name": "High Score",
   "src": "CSES",
   "diff": "Graph Algorithms",
   "url": "https://cses.fi/problemset/task/1673",
   "why": "High score: Bellman-Ford with a reachable positive cycle."
  },
  {
   "name": "787. Cheapest Flights Within K Stops",
   "src": "LeetCode",
   "diff": "Medium",
   "url": "https://leetcode.com/problems/cheapest-flights-within-k-stops/",
   "why": "Bellman-Ford limited to k+1 rounds. Why must you copy the array?"
  },
  {
   "name": "Cycle Finding",
   "src": "CSES",
   "diff": "Graph Algorithms",
   "url": "https://cses.fi/problemset/task/1197",
   "why": "Cycle finding: detect a negative cycle and print it."
  },
  {
   "name": "Shortest Routes II",
   "src": "CSES",
   "diff": "Graph Algorithms",
   "url": "https://cses.fi/problemset/task/1672",
   "why": "Shortest routes II: Floyd-Warshall, n <= 500."
  },
  {
   "name": "1334. Find the City With the Smallest Number of Neighbors at a Threshold Distance",
   "src": "LeetCode",
   "diff": "Medium",
   "url": "https://leetcode.com/problems/find-the-city-with-the-smallest-number-of-neighbors-at-a-threshold-distance/",
   "why": "Floyd-Warshall, interview phrasing."
  },
  {
   "name": "Investigation",
   "src": "CSES",
   "diff": "Graph Algorithms",
   "url": "https://cses.fi/problemset/task/1202",
   "why": "Investigation: shortest path with four quantities at once."
  }
 ],
 "P28": [
  {
   "name": "Exponentiation",
   "src": "CSES",
   "diff": "Mathematics",
   "url": "https://cses.fi/problemset/task/1095",
   "why": "Fast exponentiation, mod 1e9+7."
  },
  {
   "name": "50. Pow(x, n)",
   "src": "LeetCode",
   "diff": "Medium",
   "url": "https://leetcode.com/problems/powx-n/",
   "why": "The same, without the modulus and with negative exponents."
  },
  {
   "name": "1922. Count Good Numbers",
   "src": "LeetCode",
   "diff": "Medium",
   "url": "https://leetcode.com/problems/count-good-numbers/",
   "why": "Huge exponent: the answer is one fast power."
  },
  {
   "name": "Binomial Coefficients",
   "src": "CSES",
   "diff": "Mathematics",
   "url": "https://cses.fi/problemset/task/1079",
   "why": "Binomial coefficients: factorials plus Fermat's inverse."
  },
  {
   "name": "Distributing Apples",
   "src": "CSES",
   "diff": "Mathematics",
   "url": "https://cses.fi/problemset/task/1716",
   "why": "Distributing apples: stars and bars, mod p."
  },
  {
   "name": "Bracket Sequences I",
   "src": "CSES",
   "diff": "Mathematics",
   "url": "https://cses.fi/problemset/task/2064",
   "why": "Bracket sequences I: Catalan numbers, mod p."
  },
  {
   "name": "Exponentiation II",
   "src": "CSES",
   "diff": "Mathematics",
   "url": "https://cses.fi/problemset/task/1712",
   "why": "Exponentiation II: a^(b^c), which needs Fermat on the exponent. Careful."
  }
 ],
 "P29": [
  {
   "name": "204. Count Primes",
   "src": "LeetCode",
   "diff": "Medium",
   "url": "https://leetcode.com/problems/count-primes/",
   "why": "The sieve, and why it is n log log n."
  },
  {
   "name": "Common Divisors",
   "src": "CSES",
   "diff": "Mathematics",
   "url": "https://cses.fi/problemset/task/1081",
   "why": "Common divisors: count multiples, do not factor pairs."
  },
  {
   "name": "Counting Divisors",
   "src": "CSES",
   "diff": "Mathematics",
   "url": "https://cses.fi/problemset/task/1713",
   "why": "Counting divisors: 1e5 queries, so precompute."
  },
  {
   "name": "2427. Number of Common Factors",
   "src": "LeetCode",
   "diff": "Easy",
   "url": "https://leetcode.com/problems/number-of-common-factors/",
   "why": "Small, but forces the gcd relationship."
  },
  {
   "name": "Sum of Divisors",
   "src": "CSES",
   "diff": "Mathematics",
   "url": "https://cses.fi/problemset/task/1082",
   "why": "Sum of divisors up to 1e12: group by quotient."
  },
  {
   "name": "2521. Distinct Prime Factors of Product of Array",
   "src": "LeetCode",
   "diff": "Medium",
   "url": "https://leetcode.com/problems/distinct-prime-factors-of-product-of-array/",
   "why": "Smallest-prime-factor table in use."
  },
  {
   "name": "Prime Multiples",
   "src": "CSES",
   "diff": "Mathematics",
   "url": "https://cses.fi/problemset/task/2185",
   "why": "Prime multiples: inclusion-exclusion over primes."
  }
 ],
 "P30": [
  {
   "name": "String Matching",
   "src": "CSES",
   "diff": "String Algorithms",
   "url": "https://cses.fi/problemset/task/1753",
   "why": "String matching: hashing is the two-line solution."
  },
  {
   "name": "459. Repeated Substring Pattern",
   "src": "LeetCode",
   "diff": "Easy",
   "url": "https://leetcode.com/problems/repeated-substring-pattern/",
   "why": "Do it with hashing, then with the KMP failure function."
  },
  {
   "name": "Finding Borders",
   "src": "CSES",
   "diff": "String Algorithms",
   "url": "https://cses.fi/problemset/task/1732",
   "why": "Finding borders: every prefix that is also a suffix."
  },
  {
   "name": "Repeating Substring",
   "src": "CSES",
   "diff": "String Algorithms",
   "url": "https://cses.fi/problemset/task/2106",
   "why": "Repeating substring: binary search on length plus a hash set."
  },
  {
   "name": "1044. Longest Duplicate Substring",
   "src": "LeetCode",
   "diff": "Hard",
   "url": "https://leetcode.com/problems/longest-duplicate-substring/",
   "why": "The same binary search, interview phrasing. Mind collisions."
  },
  {
   "name": "Distinct Substrings",
   "src": "CSES",
   "diff": "String Algorithms",
   "url": "https://cses.fi/problemset/task/2105",
   "why": "Distinct substrings: counting with hashes."
  },
  {
   "name": "1316. Distinct Echo Substrings",
   "src": "LeetCode",
   "diff": "Hard",
   "url": "https://leetcode.com/problems/distinct-echo-substrings/",
   "why": "Hashes plus a small observation about halves."
  }
 ],
 "P31": [
  {
   "name": "28. Find the Index of the First Occurrence in a String",
   "src": "LeetCode",
   "diff": "Easy",
   "url": "https://leetcode.com/problems/find-the-index-of-the-first-occurrence-in-a-string/",
   "why": "Write KMP, not indexOf. Then trace the failure function by hand."
  },
  {
   "name": "String Matching",
   "src": "CSES",
   "diff": "String Algorithms",
   "url": "https://cses.fi/problemset/task/1753",
   "why": "String matching with KMP or Z, all occurrences."
  },
  {
   "name": "1392. Longest Happy Prefix",
   "src": "LeetCode",
   "diff": "Hard",
   "url": "https://leetcode.com/problems/longest-happy-prefix/",
   "why": "The failure function's last value, and nothing else."
  },
  {
   "name": "Finding Borders",
   "src": "CSES",
   "diff": "String Algorithms",
   "url": "https://cses.fi/problemset/task/1732",
   "why": "Finding borders: follow the failure chain."
  },
  {
   "name": "Finding Periods",
   "src": "CSES",
   "diff": "String Algorithms",
   "url": "https://cses.fi/problemset/task/1733",
   "why": "Finding periods: n - border, and why that is a period."
  },
  {
   "name": "214. Shortest Palindrome",
   "src": "LeetCode",
   "diff": "Hard",
   "url": "https://leetcode.com/problems/shortest-palindrome/",
   "why": "KMP on s + '#' + reverse(s). Say why the separator matters."
  },
  {
   "name": "2223. Sum of Scores of Built Strings",
   "src": "LeetCode",
   "diff": "Hard",
   "url": "https://leetcode.com/problems/sum-of-scores-of-built-strings/",
   "why": "The Z-array, straight up."
  }
 ],
 "P32": [
  {
   "name": "208. Implement Trie (Prefix Tree)",
   "src": "LeetCode",
   "diff": "Medium",
   "url": "https://leetcode.com/problems/implement-trie-prefix-tree/",
   "why": "Build it from an array of children, not a map, and know the cost."
  },
  {
   "name": "648. Replace Words",
   "src": "LeetCode",
   "diff": "Medium",
   "url": "https://leetcode.com/problems/replace-words/",
   "why": "Shortest matching prefix: walk until a word end."
  },
  {
   "name": "211. Design Add and Search Words Data Structure",
   "src": "LeetCode",
   "diff": "Medium",
   "url": "https://leetcode.com/problems/design-add-and-search-words-data-structure/",
   "why": "Wildcards turn the walk into a small DFS."
  },
  {
   "name": "212. Word Search II",
   "src": "LeetCode",
   "diff": "Hard",
   "url": "https://leetcode.com/problems/word-search-ii/",
   "why": "Trie plus grid backtracking; prune dead branches."
  },
  {
   "name": "421. Maximum XOR of Two Numbers in an Array",
   "src": "LeetCode",
   "diff": "Medium",
   "url": "https://leetcode.com/problems/maximum-xor-of-two-numbers-in-an-array/",
   "why": "The bit trie: greedy from the top bit."
  },
  {
   "name": "Maximum Xor Subarray",
   "src": "CSES",
   "diff": "Bitwise Operations",
   "url": "https://cses.fi/problemset/task/1655",
   "why": "Maximum XOR subarray: prefix XORs into the same bit trie."
  },
  {
   "name": "1803. Count Pairs With XOR in a Range",
   "src": "LeetCode",
   "diff": "Hard",
   "url": "https://leetcode.com/problems/count-pairs-with-xor-in-a-range/",
   "why": "Counting on a bit trie, which is a real step up."
  }
 ],
 "P33": [
  {
   "name": "509. Fibonacci Number",
   "src": "LeetCode",
   "diff": "Easy",
   "url": "https://leetcode.com/problems/fibonacci-number/",
   "why": "Write the 2x2 matrix version even though n is tiny. It is the template."
  },
  {
   "name": "Fibonacci Numbers",
   "src": "CSES",
   "diff": "Mathematics",
   "url": "https://cses.fi/problemset/task/1722",
   "why": "Fibonacci for n up to 1e18. Now the matrix is the only way."
  },
  {
   "name": "Throwing Dice",
   "src": "CSES",
   "diff": "Mathematics",
   "url": "https://cses.fi/problemset/task/1096",
   "why": "Throwing dice: a k-term recurrence as a k x k matrix."
  },
  {
   "name": "Graph Paths I",
   "src": "CSES",
   "diff": "Mathematics",
   "url": "https://cses.fi/problemset/task/1723",
   "why": "Graph paths I: the adjacency matrix to the k-th power counts walks."
  },
  {
   "name": "935. Knight Dialer",
   "src": "LeetCode",
   "diff": "Medium",
   "url": "https://leetcode.com/problems/knight-dialer/",
   "why": "Same idea; the naive DP passes, so do it both ways and compare."
  },
  {
   "name": "552. Student Attendance Record II",
   "src": "LeetCode",
   "diff": "Hard",
   "url": "https://leetcode.com/problems/student-attendance-record-ii/",
   "why": "Small state machine, huge n: build the transition matrix."
  },
  {
   "name": "Graph Paths II",
   "src": "CSES",
   "diff": "Mathematics",
   "url": "https://cses.fi/problemset/task/1724",
   "why": "Graph paths II: min-plus matrix product. Same skeleton, different semiring."
  }
 ],
 "P34": [
  {
   "name": "Apple Division",
   "src": "CSES",
   "diff": "Introductory Problems",
   "url": "https://cses.fi/problemset/task/1623",
   "why": "Apple division: 2^20 by brute force, and the halved version as practice."
  },
  {
   "name": "454. 4Sum II",
   "src": "LeetCode",
   "diff": "Medium",
   "url": "https://leetcode.com/problems/4sum-ii/",
   "why": "Two halves, one map. The cleanest meet in the middle there is."
  },
  {
   "name": "Meet in the Middle",
   "src": "CSES",
   "diff": "Advanced Techniques",
   "url": "https://cses.fi/problemset/task/1628",
   "why": "Meet in the middle: n <= 40, the canonical problem."
  },
  {
   "name": "1755. Closest Subsequence Sum",
   "src": "LeetCode",
   "diff": "Hard",
   "url": "https://leetcode.com/problems/closest-subsequence-sum/",
   "why": "Sort one half and binary search it from the other."
  },
  {
   "name": "2035. Partition Array Into Two Arrays to Minimize Sum Difference",
   "src": "LeetCode",
   "diff": "Hard",
   "url": "https://leetcode.com/problems/partition-array-into-two-arrays-to-minimize-sum-difference/",
   "why": "The hard version: split by popcount before searching."
  }
 ]
};
