#!/usr/bin/env python3
"""Regenerate derived files from knowledge-graph.json. Run after editing the graph.

  content/graph.js          the graph, loadable by pages opened from file:// (no fetch)
  lessons/<ID>-<slug>.html  one thin shell per topic; the lesson itself is content/<ID>.js
"""
import json
import re
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent

SHELL = """<!DOCTYPE html>
<html lang="en">
<head>
<meta charset="utf-8">
<meta name="viewport" content="width=device-width, initial-scale=1">
<title>{id} · {title}</title>
<link rel="stylesheet" href="../assets/course.css">
</head>
<body data-page="lesson" data-root="../" data-topic="{id}">
<div id="app"></div>
<noscript>This lesson needs JavaScript.</noscript>
<script src="../content/graph.js"></script>
<script src="../assets/engine.js"></script>
<script src="../content/{id}.js"></script>
</body>
</html>
"""


def slug(title):
    return re.sub(r"[^a-z0-9]+", "-", title.lower()).strip("-")[:40].rstrip("-")


def main():
    g = json.loads((ROOT / "knowledge-graph.json").read_text())
    topics = {}
    for t in g["topics"]:
        href = f"lessons/{t['id']}-{slug(t['title'])}.html"
        topics[t["id"]] = {"title": t["title"], "module": t["module"], "prereqs": t["prereqs"],
                           "key_prereqs": t["key_prereqs"], "href": href}
        (ROOT / href).write_text(SHELL.format(id=t["id"], title=t["title"]))
    data = {"modules": {m["id"]: m["title"] for m in g["modules"]}, "topics": topics}
    (ROOT / "content").mkdir(exist_ok=True)
    (ROOT / "content" / "graph.js").write_text(
        "// Generated by tools/build.py from knowledge-graph.json. Do not edit.\n"
        "window.COURSE = window.COURSE || {};\nCOURSE.graph = " + json.dumps(data, indent=1) + ";\n")
    print(f"wrote content/graph.js and {len(topics)} lesson shells")


if __name__ == "__main__":
    main()
